import { Internship } from '../types/internship';

export const fallbackData: Internship[] = [
  {
    id: '1',
    title: 'Software Development Intern',
    company: 'TechStack India',
    location: 'Bangalore',
    salary: '₹15,000 - ₹25,000 /month',
    postedDate: '2025-04-10',
    deadline: '2025-05-15',
    type: 'internship',
    role: 'Software Developer',
    description: 'We are looking for a passionate Software Development Intern to join our engineering team. You will be working on real-world projects using React, Node.js, and MongoDB. This is a 6-month internship with the possibility of a full-time offer.',
    skills: ['React', 'JavaScript', 'Node.js', 'MongoDB'],
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
    applyLink: 'https://www.techstackindia.com/careers',
  },
  {
    id: '2',
    title: 'Data Science Intern',
    company: 'Analytics Vidya',
    location: 'Hyderabad',
    salary: '₹20,000 - ₹30,000 /month',
    postedDate: '2025-04-05',
    deadline: '2025-05-05',
    type: 'internship',
    role: 'Data Scientist',
    description: 'Join our data science team and work on cutting-edge ML models. You will be analyzing large datasets, building predictive models, and presenting insights to stakeholders.',
    skills: ['Python', 'Machine Learning', 'SQL', 'Data Visualization'],
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg',
    applyLink: 'https://www.analyticsvidya.com/careers',
  },
  {
    id: '3',
    title: 'Frontend Developer',
    company: 'Infosys',
    location: 'Chennai',
    salary: '₹7,00,000 - ₹9,00,000 /year',
    postedDate: '2025-04-12',
    deadline: '2025-05-20',
    type: 'job',
    role: 'Frontend Developer',
    description: 'We are seeking a skilled Frontend Developer to join our team. The ideal candidate will have experience with modern JavaScript frameworks and responsive design principles.',
    skills: ['React', 'HTML', 'CSS', 'JavaScript', 'TypeScript'],
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg',
    applyLink: 'https://career.infosys.com',
  },
  {
    id: '4',
    title: 'UI/UX Design Intern',
    company: 'DesignHub',
    location: 'Mumbai',
    salary: '₹12,000 - ₹18,000 /month',
    postedDate: '2025-04-08',
    deadline: '2025-05-10',
    type: 'internship',
    role: 'UI/UX Designer',
    description: 'Looking for a creative UI/UX Design Intern to join our design team. You will be working on designing user interfaces for web and mobile applications.',
    skills: ['Figma', 'Adobe XD', 'UI Design', 'Wireframing'],
    applyLink: 'https://www.designhub.in/careers',
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'TCS',
    location: 'Pune',
    salary: '₹8,00,000 - ₹12,00,000 /year',
    postedDate: '2025-04-03',
    deadline: '2025-05-03',
    type: 'job',
    role: 'DevOps Engineer',
    description: 'TCS is looking for a DevOps Engineer to build and maintain CI/CD pipelines and infrastructure as code for our clients.',
    skills: ['Docker', 'Kubernetes', 'Jenkins', 'AWS', 'Terraform'],
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg',
    applyLink: 'https://www.tcs.com/careers',
  },
  {
    id: '6',
    title: 'Marketing Intern',
    company: 'Bharti Airtel',
    location: 'Delhi',
    salary: '₹10,000 - ₹15,000 /month',
    postedDate: '2025-04-15',
    deadline: '2025-05-15',
    type: 'internship',
    role: 'Marketing',
    description: 'Airtel is looking for a Marketing Intern to help with social media campaigns, content creation, and market research. This is a 3-month internship with the possibility of extension.',
    skills: ['Social Media Marketing', 'Content Creation', 'Market Research'],
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Bharti_Airtel_Limited_logo.svg',
    applyLink: 'https://careers.airtel.com',
  },
  {
    id: '7',
    title: 'Machine Learning Engineer',
    company: 'Flipkart',
    location: 'Bangalore',
    salary: '₹12,00,000 - ₹18,00,000 /year',
    postedDate: '2025-04-01',
    deadline: '2025-05-01',
    type: 'job',
    role: 'Machine Learning Engineer',
    description: 'Flipkart is seeking a Machine Learning Engineer to develop and deploy ML models for recommendation systems and customer behavior analysis.',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Deep Learning', 'NLP'],
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/7/74/Flipkart_logo.svg',
    applyLink: 'https://www.flipkartcareers.com',
  },
  {
    id: '8',
    title: 'Web Development Intern',
    company: 'Saveetha Engineering College',
    location: 'Chennai',
    salary: '₹8,000 - ₹12,000 /month',
    postedDate: '2025-04-14',
    deadline: '2025-05-14',
    type: 'internship',
    role: 'Web Developer',
    description: 'Saveetha Engineering College is looking for Web Development Interns to help build and maintain the college website and internal applications.',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    companyLogo: 'https://saveetha.ac.in/wp-content/uploads/2023/09/saveetha-logo-1.png',
    applyLink: 'https://www.saveetha.ac.in/careers',
  }
];
